### ISSUE TITLE
TypeError: activate() got an unexpected keyword argument 'ctx'

### ISSUE THREAD

**Issue by khurshid-alam** [tuxcanfly/kupfer-plugins#1]
On Ubuntu 18.04 it doesn't seem to work (kupfer version 319 python3)

```
Traceback (most recent call last):
  File "/usr/share/kupfer/kupfer/ui/browser.py", line 1849, in _activate
    self.data_controller.activate(ui_ctx=self._make_gui_ctx())
  File "/usr/share/kupfer/kupfer/core/data.py", line 811, in activate
    res, ret = ctx.run(leaf, action, sobject, ui_ctx=ui_ctx)
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 327, in run
    ret = activate_action(execution_token, obj, action, iobj)
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 81, in activate_action
    return _activate_action_single(obj, action, iobj, kwargs)
  File "/usr/share/kupfer/kupfer/core/commandexec.py", line 89, in _activate_action_single
    ret = action.activate(obj, **kwargs)
TypeError: activate() got an unexpected keyword argument 'ctx'
```

Also why does it have the same shortcut as open (ctrl+o) ?

**Comment by khurshid-alam** [comment]
@tuxcanfly 

Hi, can you reply ?
